name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]   # repo'nun ana branch'i main değilse burayı değiştir
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # optional dependency hatalarını önlemek için
      - name: Install dependencies (no optional)
        run: npm ci --omit=optional

      - name: Build
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Secret adı Azure'un oluşturduğu uzun adla eşleşmeli
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SEA_061C64D1E }}
          action: upload
          app_location: /
          output_location: dist
