name: CI - Vite Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # ⚠️ Kritik: Windows lockfile'ı CI'da kullanma
      - name: Clean workspace (lockfile & node_modules)
        run: rm -rf node_modules package-lock.json

      # Linux runner kendi platformuna uygun optional native paketi (rollup-linux-*) çözer
      - name: Install dependencies (fresh, include optional)
        run: npm install --include=optional

      - name: Rebuild native deps (best-effort)
        run: npm rebuild || true

      - name: Print versions (diagnostic)
        run: |
          node -v
          npm -v
          node -e "try{console.log('rollup version:', require('rollup/package.json').version)}catch(e){console.error('rollup not resolvable')}"

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
