name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean install (fresh lock)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Optional dep workaround for Rollup
        run: |
          # Ubuntu/gnu runner için:
          npm install @rollup/rollup-linux-x64-gnu --save-optional
          # Eğer runner Alpine/musl olsaydı:
          # npm install @rollup/rollup-linux-x64-musl --save-optional

      - name: Build
        run: npm run build
